//import the module.
const serv = require("../modules/service");
const multer =require("multer");


// define route handler.
// exports.serviceproj = async(req,res) => {
//     try{
//      // extract title and descripation from request body
//      const{serviceName,servicePrice,serviceCategory,HsnCode,Tax,photo} = req.body;
//      //create a new Todo obj and insert in DB
//      const response = await serv.create({serviceName,servicePrice,serviceCategory,HsnCode,Tax,photo});
//      // send a json responce with a success flag
//       res.status(200).json(
//     {
//        success:true,
//         data:response,
//         message:'Entry Created Successfully'

//     }
// );
//     }
//     catch(err){
//        console.log(err);
//        res.status(500)
//        .json(
//          {
//            success:false,
//             data:"internal server error",
//             message:err.message, 
//          }
//        )
//     } 
// }

// Set up Multer storage configuration
const storage = multer.diskStorage({
    destination: function (req, file, cb) {
      cb(null, 'uploads/'); // Set the destination folder where the uploaded files will be stored
    },
    filename: function (req, file, cb) {
      const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
      cb(null, file.fieldname + '-' + uniqueSuffix + '.' + file.originalname.split('.').pop());
    }
  });
  
  const upload = multer({ storage: storage });
  
  exports.serviceproj = async (req, res) => {
    try {
      // Multer middleware to handle the 'photo' field in the request
      upload.single('photo')(req, res, async (err) => {
        if (err) {
          return res.status(400).json({
            success: false,
            data: null,
            message: 'File upload failed',
            error: err.message
          });
        }
  
        // Extract title and description from the request body
        const { serviceName, servicePrice, serviceCategory, HsnCode, Tax } = req.body;
  
        // Retrieve the filename generated by Multer
        const photo = req.file.filename;
  
        // Create a new service object and insert it into the database
        const response = await serv.create({
          serviceName,
          servicePrice,
          serviceCategory,
          HsnCode,
          Tax,
          photo
        });
  
        // Send a JSON response with a success flag
        res.status(200).json({
          success: true,
          data: response,
          message: 'Entry Created Successfully'
        });
      });
    } catch (err) {
      console.log(err);
      res.status(500).json({
        success: false,
        data: "Internal Server Error",
        message: err.message,
      });
    }
  };

//
// define route handler. for get Api.
exports.serviceproj1 = async(req,res) => {
    try{
        // featch all item from database.
         const response = await serv.find({});
      // response.
      res.status(200)
      .json(
        {
            success:true,
            response,
            message:'Entry Created Successfully'

   }
      );
        
    }
    catch(err){
        console.error(err);
        // console.log(err);
        res.status(500)
        .json(
            {
                success:false,
                 error:"internal server error",
                message: "server error", 
            }
        );
    }
}